# Generated by Django 3.0.6 on 2020-10-09 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='compo',
            field=models.CharField(default='slam', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='frame',
            field=models.CharField(default='bianchi', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wheel',
            field=models.CharField(default='spinergy', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='askFrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askFrom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='askTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='askTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
